### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/IntWarsSharp#23]
Can someone send me all the gameclient launch args for the latest lol version

Having problems with league updating :/

**Comment by chutch1122** [comment]
If you look at the fbipLoL repository on my profile you could pretty easily
modify that program to intercept and write out the game client launch
arguments

**Comment by MythicManiac** [comment]
Are you trying to get this project set up, or is this issue unrelated?

**Comment by Fighter19** [comment]
http://pastebin.com/iTQ8NwBX

From LoLPatcherProxy.


Download it, rename the file to .bat
Put this inside the folder with lol.launcher.exe

**Comment by MythicManiac** [comment]
@eddy5641 closing since this issue seems resolved

**Comment by eddy5641** [comment]
no i am trying to determine the new encrption that riot is using

**Comment by MythicManiac** [comment]
Hop over to https://discord.gg/0vmmZ6VAwXB05gB6 then, there are some other people who are working on that as well
